spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/university
    user: postgres
    password: postgres
